controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - Revolute 2
      - Revolute 4
      - Revolute 5
      - Revolute 8
      - Revolute 10
      - Revolute 12

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false

    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0

    gains:
      Revolute 2:  {p: 150.0, i: 0.01, d: 2.0}
      Revolute 4:  {p: 150.0, i: 0.01, d: 2.0}
      Revolute 5:  {p: 150.0, i: 0.01, d: 2.0}
      Revolute 8:  {p: 20.0, i: 0.01, d: 1.0}
      Revolute 10: {p: 20.0, i: 0.01, d: 1.0}
      Revolute 12: {p: 20.0, i: 0.01, d: 1.0}
